ids = [
    "elrond",
    "gandalf",
    "galadriel",
    "celeborn",
    "aragorn",
    "arwen",
    "glorfindel",
    "legolas",
    "thorin",
    "balin",
    "gloin",
    "gimli",
    "denethor",
    "boromir",
    "faramir",
    "theoden",
    "eomer",
    "eowyn",
    "bilbo",
    "frodo",
    "sam",
    "pipin",
    "merry",
    "sauron",
    "mordu",
    "witchking",
    "nazgul",
    "azog",
    "ugluk",
    "mauhur",
    "shagrat",
    "gorbag",
    "grishnagh",
    "shelob",
    "grima",
    "saruman",
    "radagast",
    "gollum",
    "tom",
    "human",
    "elf",
    "dwarf",
    "hobit",
    "orc",
    "spider",
]

if __name__ == "__main__":
    for x in ids:
        print("\\{}name & & \\{}faction & \\{}aura & \\{}ability & \\{}task \\\\ \\hline".format(x, x, x, x, x))
        
